name: Build and Push Docker Image on Release

on:
  workflow_dispatch:
    inputs:
      image_tag_version:
        description: 'The version of the image to build'
        required: true
        default: 'latest'
        type: string
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Build and test Docker image
        run: |
          docker build -f Dockerfile -t ghcr.io/kronton/${{ github.event.repository.name}}-base-image:${{ github.event.inputs.image_tag_version }} .
        env:
          DOCKER_BUILDKIT: 1  # Enable BuildKit for advanced features
          
      - name: Push Docker images
        run: |
         ghcr.io/kronton/${{ github.event.repository.name}}-base-image:${{ github.event.inputs.image_tag_version }}
